baseURL: https://sandboxdb.org/
title: SandboxDB.org
paginate: 100
languageCode: en
disablePathToLower: true

# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm

# Enable some features
enableRobotsTXT: true
enableEmoji: true

# Generate JSON
uglyurls: true
outputs:
  page: ["HTML", "JSON"]
  section: ["HTML", "JSON"]

# HTML in Markdown
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  DefaultDescription: >-
    SandboxDB.org collects sandboxing options from various GNU/Linux distributions.
  DefaultKeywords: ["sandbox", "hardening", "database", "systemd", "unit", "service", "option"]
